In [1]:
import pandas as pd

In [66]:
def go(yr, D):
    df1 = pd.read_excel('/Users/leejunki/weather/'+str(yr)+'/'+'_1.xlsx', encoding='euc-kr')
    df2 = pd.read_excel('/Users/leejunki/weather/'+str(yr)+'/'+'_2.xlsx', encoding='euc-kr')
    df3 = pd.read_excel('/Users/leejunki/weather/'+str(yr)+'/'+'_3.xlsx', encoding='euc-kr')
    df4 = pd.read_excel('/Users/leejunki/weather/'+str(yr)+'/'+'_4.xlsx', encoding='euc-kr')
    
    res1 = df1.groupby([df1['지역'], df1['측정소코드'], df1['측정소명'], df1['측정일시']//100],
                       as_index=False).mean()
    res2 = df2.groupby([df2['지역'], df2['측정소코드'], df2['측정소명'], df2['측정일시']//100],
                       as_index=False).mean()
    res3 = df3.groupby([df3['지역'], df3['측정소코드'], df3['측정소명'], df3['측정일시']//100],
                       as_index=False).mean()
    res4 = df4.groupby([df4['지역'], df4['측정소코드'], df4['측정소명'], df4['측정일시']//100],
                       as_index=False).mean()
    
    res1['일시'] = res1['측정일시'] // 100
    res2['일시'] = res2['측정일시'] // 100
    res3['일시'] = res3['측정일시'] // 100
    res4['일시'] = res4['측정일시'] // 100
    
    cols = res1.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res1 = res1[cols]

    cols = res2.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res2 = res2[cols]

    cols = res3.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res3 = res3[cols]

    cols = res4.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res4 = res4[cols]
    
    res1['일시'] = res1['일시'].astype('int')
    del res1['측정일시']

    res2['일시'] = res2['일시'].astype('int')
    del res2['측정일시']

    res3['일시'] = res3['일시'].astype('int')
    del res3['측정일시']

    res4['일시'] = res4['일시'].astype('int')
    del res4['측정일시']
    
    res = pd.concat([res1, res2, res3, res4])
    res.groupby([res['지역'], res['일시']], as_index=False).mean()
    data = res.groupby([res['지역'], res['일시']], as_index=False).mean()
    data['지역명'] = data.apply(lambda row: row['지역'][:2], axis=1)
    temp = data.groupby([data['지역명'], data['일시']], as_index=False).mean()
    
    del temp['측정소코드']
    temp = temp.replace({"지역명": D})
    temp.to_csv('/Users/leejunki/weather/finedust'+str(yr)+'.csv', encoding='euc-kr')

In [150]:
def go_csv(yr, D):
    df1 = pd.read_csv('/Users/leejunki/weather/'+str(yr)+'/'+'_1.csv', encoding='euc-kr')
    df2 = pd.read_csv('/Users/leejunki/weather/'+str(yr)+'/'+'_2.csv', encoding='euc-kr')
    df3 = pd.read_csv('/Users/leejunki/weather/'+str(yr)+'/'+'_3.csv', encoding='euc-kr')
    df4 = pd.read_csv('/Users/leejunki/weather/'+str(yr)+'/'+'_4.csv', encoding='euc-kr')

    res1 = df1.groupby([df1['지역'], df1['측정소코드'], df1['측정소명'], df1['측정일시']//100],
                       as_index=False).mean()
    res2 = df2.groupby([df2['지역'], df2['측정소코드'], df2['측정소명'], df2['측정일시']//100],
                       as_index=False).mean()
    res3 = df3.groupby([df3['지역'], df3['측정소코드'], df3['측정소명'], df3['측정일시']//100],
                       as_index=False).mean()
    res4 = df4.groupby([df4['지역'], df4['측정소코드'], df4['측정소명'], df4['측정일시']//100],
                       as_index=False).mean()

    res1['일시'] = res1['측정일시'] // 100
    res2['일시'] = res2['측정일시'] // 100
    res3['일시'] = res3['측정일시'] // 100
    res4['일시'] = res4['측정일시'] // 100

    cols = res1.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res1 = res1[cols]

    cols = res2.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res2 = res2[cols]

    cols = res3.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res3 = res3[cols]

    cols = res4.columns.tolist()
    cols = cols[:3] + [cols[-1]] + cols[3:-1]
    res4 = res4[cols]

    res1['일시'] = res1['일시'].astype('int')
    del res1['측정일시']

    res2['일시'] = res2['일시'].astype('int')
    del res2['측정일시']

    res3['일시'] = res3['일시'].astype('int')
    del res3['측정일시']

    res4['일시'] = res4['일시'].astype('int')
    del res4['측정일시']

    res = pd.concat([res1, res2, res3, res4])
    res.groupby([res['지역'], res['일시']], as_index=False).mean()
    data = res.groupby([res['지역'], res['일시']], as_index=False).mean()
    data['지역명'] = data.apply(lambda row: row['지역'][:2], axis=1)
    temp = data.groupby([data['지역명'], data['일시']], as_index=False).mean()

    del temp['측정소코드']
    temp = temp.replace({"지역명": D})
    temp.to_csv('/Users/leejunki/weather/finedust'+str(yr)+'.csv', encoding='euc-kr')

In [151]:
yr = 2002

In [152]:
A = [11, 26, 27, 28, 29, 30, 31, 36, 41, 42, 43, 44, 45, 46, 47, 48, 49]
B = ['서울','부산','대구','인천','광주','대전','울산','세종','경기','강원','충북','충남',
    '전북','전남','경북','경남','제주']
D = dict(zip(B, A))

In [153]:
f = {'2002':'xlsx','2003':'xlsx','2004':'xlsx','2005':'xlsx','2006':'xlsx','2007':'xlsx',
     '2008':'xlsx','2009':'xlsx','2010':'xlsx','2011':'xlsx','2012':'xlsx','2013':'xlsx',
     '2014':'csv','2015':'csv','2016':'csv','2017':'xlsx','2018':'xlsx'}

In [154]:
f = {'2016':'csv','2017':'xlsx','2018':'xlsx'}

In [155]:
for yr, form in f.items():
    if form == "xlsx":
        go(yr, D)
    else:
        go_csv(yr, D)

In [55]:
res = pd.concat([res1, res2, res3, res4])
data = res.groupby([res['지역'], res['일시']], as_index=False).mean()

In [58]:
data = res.groupby([res['지역'], res['일시']], as_index=False).mean()

In [59]:
data.head()

,지역,일시,측정소코드,SO2,CO,O3,NO2,PM10
0,강원 강릉시,20020101,632132.0,0.001042,0.829167,0.032667,0.011083,36.625000
1,강원 강릉시,20020102,632132.0,0.001167,0.916667,0.035958,0.010917,37.166667
2,강원 강릉시,20020103,632132.0,0.001208,0.895833,0.036042,0.011042,38.875000
3,강원 강릉시,20020104,632132.0,0.001083,1.000000,0.033292,0.010958,37.708333
4,강원 강릉시,20020105,632132.0,0.001000,0.862500,0.030417,0.010792,-563.666667

In [122]:
temp = temp.replace({"지역명": D})

In [124]:
temp.to_csv('finedust'+str(yr)+'.csv', encoding='euc-kr', index=False)

In [123]:
temp

,지역명,일시,SO2,CO,O3,NO2,PM10,PM25
0,42,20160101,0.003714,0.751389,0.020653,0.017372,53.419192,43.823962
1,42,20160102,0.004111,0.679861,0.027213,0.015362,45.668981,38.521739
2,42,20160103,0.005682,0.965046,0.025720,0.018331,67.046759,53.994746
3,42,20160104,0.004829,0.744887,0.032708,0.016339,72.317130,55.925000
4,42,20160105,0.003348,0.487235,0.024958,0.013339,25.939383,16.179892
5,42,20160106,0.003923,0.568087,0.021593,0.014820,42.880435,27.898755
6,42,20160107,0.003791,0.582197,0.021160,0.016245,44.296296,31.265217
7,42,20160108,0.003800,0.524769,0.022241,0.014140,35.248188,21.720833
8,42,20160109,0.003662,0.525231,0.024935,0.013681,34.537037,23.354167
9,42,20160110,0.004768,0.594444,0.028301,0.013551,33.141204,23.125000
10,42,20160111,0.003927,0.568730,0.025555,0.014530,31.199074,20.838420
11,42,20160112,0.003721,0.576414,0.019830,0.018652,35.807870,23.731439
12,42,20160113,0.003174,0.475967,0.024718,0.014999,36.314103,24.170685
13,42,20160114,0.003574,0.438568,0.027875,0.013675,33.272231,21.846812
14,42,20160115,0.004235,0.601620,0.019873,0.021822,44.493623,35.575906
15,42,20160116,0.004994,0.700231,0.021271,0.020137,54.692130,44.415909
16,42,20160117,0.004961,0.829398,0.018762,0.020472,63.812500,53.566667
17,42,20160118,0.003404,0.566526,0.026090,0.013224,52.338215,35.218643
18,42,20160119,0.002953,0.342181,0.030638,0.007435,31.954618,14.398030
19,42,20160120,0.003306,0.516662,0.021602,0.014250,37.822341,25.438676
20,42,20160121,0.004094,0.677108,0.016148,0.021271,47.493031,34.379545
21,42,20160122,0.003556,0.668935,0.020001,0.019905,44.907407,32.204819
22,42,20160123,0.003294,0.440972,0.030840,0.008909,32.417593,19.400119
23,42,20160124,0.004178,0.507870,0.029734,0.007855,37.532810,24.880710
24,42,20160125,0.003718,0.607126,0.021333,0.016816,42.500842,26.244824
25,42,20160126,0.004721,0.735417,0.022779,0.020022,55.462963,35.637500
26,42,20160127,0.006370,0.892151,0.026092,0.020850,66.524832,49.358333
27,42,20160128,0.006111,0.909907,0.020671,0.022726,59.784722,42.964855
28,42,20160129,0.004968,0.788624,0.025602,0.017025,35.458333,30.042063
29,42,20160130,0.004206,0.740278,0.021880,0.016508,24.578704,22.929351
...,...,...,...,...,...,...,...,...
6192,43,20161202,0.003853,0.651776,0.008645,0.027250,40.007659,22.031944
6193,43,20161203,0.004017,0.906597,0.006501,0.033245,63.105324,40.241667
6194,43,20161204,0.004337,1.166898,0.004162,0.032764,75.802083,57.299638
6195,43,20161205,0.005100,1.022180,0.018321,0.025425,91.430103,65.958333
6196,43,20161206,0.003648,0.437510,0.017312,0.018810,31.576460,18.286051
6197,43,20161207,0.003565,0.918419,0.004997,0.029584,51.321970,35.567478
6198,43,20161208,0.003415,1.087924,0.007599,0.028841,73.838001,55.631220
6199,43,20161209,0.003526,0.700714,0.017258,0.019937,43.825735,34.076932
6200,43,20161210,0.003331,0.665856,0.010216,0.024025,39.704006,28.087742
6201,43,20161211,0.003178,0.779745,0.007623,0.026529,44.979972,31.972222
6202,43,20161212,0.004157,0.974653,0.004678,0.030462,61.129630,40.137500
6203,43,20161213,0.004475,0.970023,0.006895,0.030470,57.765046,43.332488
6204,43,20161214,0.003651,0.699950,0.007601,0.026653,58.472222,44.018056
6205,43,20161215,0.003266,0.448495,0.017197,0.019701,35.870536,23.197222
6206,43,20161216,0.004133,0.633545,0.012591,0.023010,34.884762,19.980797
6207,43,20161217,0.005251,0.835880,0.011228,0.027608,47.825231,30.012742
6208,43,20161218,0.003769,0.990394,0.008988,0.023629,52.008102,37.806944
6209,43,20161219,0.003535,0.919160,0.004958,0.024839,44.181382,32.165025
6210,43,20161220,0.003584,1.069928,0.006513,0.024457,62.984954,45.780556
6211,43,20161221,0.003243,0.933512,0.007385,0.024043,49.725694,35.778804
6212,43,20161222,0.002565,0.614539,0.020299,0.013010,18.343247,12.870833
6213,43,20161223,0.002459,0.469213,0.022289,0.011187,33.300926,25.168841
6214,43,20161224,0.002958,0.695255,0.012509,0.019744,61.488426,51.697826
6215,43,20161225,0.002901,1.071417,0.004163,0.024012,68.449239,56.071920
6216,43,20161226,0.002928,1.030903,0.004118,0.025829,43.170139,35.922464
6217,43,20161227,0.002783,0.578320,0.014949,0.020626,37.355446,27.647222
6218,43,20161228,0.003252,0.646506,0.007748,0.026813,43.776991,27.484031
6219,43,20161229,0.003539,0.590856,0.012675,0.023957,37.615388,21.397585
6220,43,20161230,0.003543,0.693171,0.009639,0.024714,35.230425,23.419143
6221,43,20161231,0.004466,0.994329,0.005969,0.025789,50.515902,40.820833