In [1]:
import pandas as pd
import numpy as np

In [2]:
yr = 2016

In [3]:
df = pd.read_csv('da_'+str(yr)+'.csv', encoding='euc-kr')

In [4]:
df

,기준년도,가입자일련번호,진료내역일련번호,성별코드,연령대코드(5세단위),시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,부상병코드,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,총처방일수,데이터공개일자
0,2016,1,34153116,2,2,45,20160817,3,14,L209,L0888,1,1,0.15,14410,4300,10110,1,20171218
1,2016,2,46374827,2,8,41,20160202,3,1,J209,J304,1,1,0.15,10300,3000,7300,3,20171218
2,2016,2,3115110,2,8,41,20160407,3,1,J209,J304,1,1,0.15,10300,3000,7300,2,20171218
3,2016,2,50348269,2,8,41,20160104,3,1,A099,K291,1,1,0.15,14410,4300,10110,2,20171218
4,2016,2,15822952,2,8,41,20160130,3,13,J40,J304,1,1,0.15,17980,5300,12680,5,20171218
5,2016,2,42990877,2,8,41,20160416,3,13,J40,J304,1,1,0.15,17980,5300,12680,4,20171218
6,2016,2,40156783,2,8,41,20160820,3,13,J40,J304,1,1,0.15,17980,5300,12680,3,20171218
7,2016,2,30696074,2,8,41,20160204,3,13,J40,J304,1,1,0.15,11810,3500,8310,3,20171218
8,2016,2,42883324,2,8,41,20160420,3,13,J40,J304,1,1,0.15,11810,3500,8310,2,20171218
9,2016,2,8473641,2,8,41,20160224,3,13,J40,J304,1,1,0.15,11810,3500,8310,3,20171218
10,2016,2,1564113,2,8,41,20160203,3,1,J029,M1399,1,1,0.15,12340,3700,8640,0,20171218
11,2016,2,12401727,2,8,41,20160328,3,7,M940,R074,1,1,0.25,31730,15800,15930,7,20171218
12,2016,2,12158024,2,8,41,20160316,3,5,S2340,K291,1,1,0.15,25380,7600,17780,3,20171218
13,2016,2,51314132,2,8,41,20161210,3,15,N300,R1039,1,1,0.15,19810,5900,13910,3,20171218
14,2016,2,19876304,2,8,41,20160816,3,15,N300,K297,1,1,0.15,21620,6400,15220,3,20171218
15,2016,2,57400233,2,8,41,20160715,3,13,R42,K296,1,1,0.15,25480,7600,17880,3,20171218
16,2016,3,62655904,2,6,11,20160129,3,1,J209,J060,1,1,0.15,15920,4700,11220,3,20171218
17,2016,3,10328984,2,6,11,20160203,3,13,J042,J304,1,1,0.15,15920,4700,11220,3,20171218
18,2016,3,858036,2,6,11,20160519,3,13,J0390,J060,1,1,0.15,15920,4700,11220,3,20171218
19,2016,3,17499764,2,6,11,20160516,3,13,J0390,J042,1,1,0.15,25500,7600,17900,2,20171218
20,2016,3,17071958,2,6,11,20160402,3,12,H1629,H400,1,1,0.15,33590,10000,23590,1,20171218
21,2016,4,53135011,2,7,29,20160902,3,13,H6640,H628,1,1,0.15,10300,3000,7300,3,20171218
22,2016,4,40109035,2,7,29,20160831,3,13,H6640,J029,1,1,0.15,10300,3000,7300,2,20171218
23,2016,4,53030834,2,7,29,20160924,3,13,J0190,J304,1,1,0.15,12550,3700,8850,7,20171218
24,2016,4,55640558,2,7,29,20160827,3,13,H6640,J029,1,1,0.15,12550,3700,8850,14,20171218
25,2016,4,15779992,2,7,29,20160123,3,13,J0390,J304,1,1,0.15,17980,5300,12680,3,20171218
26,2016,4,54365120,2,7,29,20161010,3,13,H66000,K291,1,1,0.15,17980,5300,12680,4,20171218
27,2016,4,5308192,2,7,29,20160928,3,13,J060,J0190,1,1,0.15,11810,3500,8310,3,20171218
28,2016,4,25159900,2,7,29,20160325,3,4,R222,K297,1,1,0.25,12980,6400,6580,7,20171218
29,2016,4,12375423,2,7,29,20160319,3,4,R222,K297,1,1,0.25,17070,8500,8570,7,20171218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12540317,2016,999996,27467842,1,15,48,20160927,3,13,J4500,J060,1,1,0.15,11920,1500,10420,5,20171218
12540318,2016,999996,51792807,1,15,48,20161230,3,12,H0204,H108,1,1,0.15,13270,1500,11770,0,20171218
12540319,2016,999996,60658488,1,15,48,20160106,3,4,J40,J00,1,1,0.15,12130,1500,10630,2,20171218
12540320,2016,999996,60658487,1,15,48,20160108,3,4,J40,J00,1,1,0.15,12130,1500,10630,2,20171218
12540321,2016,999996,43420228,1,15,48,20160704,3,13,J4500,J060,1,1,0.15,16030,4800,11230,2,20171218
12540322,2016,999996,27643592,1,15,48,20160919,3,13,J4500,J060,1,1,0.15,16030,4800,11230,2,20171218
12540323,2016,999996,19488749,1,15,48,20161116,3,13,J4500,J209,1,1,0.15,16030,4800,11230,3,20171218
12540324,2016,999996,61315709,1,15,48,20160524,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540325,2016,999996,61315712,1,15,48,20160520,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540326,2016,999996,61315713,1,15,48,20160516,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540327,2016,999996,46938802,1,15,48,20160610,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540328,2016,999996,46938801,1,15,48,20160602,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540329,2016,999996,15587710,1,15,48,20160311,3,4,M5456,J00,1,1,0.15,17350,5200,12150,3,20171218
12540330,2016,999996,53892321,1,15,48,20160615,3,5,M4809,K291,1,1,0.15,21820,6500,15320,2,20171218
12540331,2016,999996,5643888,1,15,48,20160930,3,14,L230,L233,1,1,0.15,16120,4800,11320,4,20171218
12540332,2016,999996,25202721,1,15,48,20160309,3,4,M5456,L500,1,1,0.15,21460,6400,15060,3,20171218
12540333,2016,999997,18473255,1,12,41,20161028,8,0,I109,L309,1,30,0.00,42020,12600,29420,0,20171218
12540334,2016,999997,16624282,1,12,41,20160824,8,0,I109,M6261,1,30,0.00,42020,12600,29420,0,20171218
12540335,2016,999997,51748710,1,12,41,20161227,8,0,I109,M6261,1,30,0.00,42020,12600,29420,0,20171218
12540336,2016,999997,1329853,1,12,41,20160229,8,0,J00,M6261,1,5,0.00,9520,900,8620,0,20171218
12540337,2016,999998,8981599,1,5,27,20160420,3,13,J209,J069,1,1,0.15,14410,4300,10110,3,20171218
12540338,2016,999998,19403294,1,5,27,20161128,3,14,L600,L0220,1,1,0.15,15410,4600,10810,4,20171218
12540339,2016,999998,7684462,1,5,27,20161202,3,14,L600,L0220,1,1,0.15,15410,4600,10810,3,20171218
12540340,2016,999998,19399447,1,5,27,20161126,3,14,L600,L0220,1,1,0.15,17660,5200,12460,1,20171218
12540341,2016,999998,31825051,1,5,27,20160218,3,4,M79170,K30,1,1,0.15,20910,6200,14710,5,20171218
12540342,2016,999998,19569485,1,5,27,20161125,3,14,L600,L0220,1,1,0.15,56560,16900,39660,1,20171218
12540343,2016,999999,47679493,2,9,27,20161117,3,14,L0888,L248,1,1,0.15,14410,4300,10110,3,20171218
12540344,2016,999999,52853246,2,9,27,20160905,3,13,H6038,K297,1,1,0.15,15150,4500,10650,2,20171218
12540345,2016,999999,57327927,2,9,27,20160712,3,12,H0411,H1688,1,1,0.15,16870,5000,11870,1,20171218
12540346,2016,1000000,39962109,2,7,26,20160815,3,12,H109,H108,1,1,0.15,20210,6000,14210,1,20171218

In [9]:
eye = df[df['주상병코드'].str.startswith('H041')]

In [10]:
eye = eye[['시도코드', '요양개시일자', '주상병코드', '가입자일련번호']]

In [24]:
res = eye.pivot_table(values=[], index=['시도코드', '요양개시일자'], columns=['주상병코드'], aggfunc=len, fill_value=0)

In [59]:
res.to_csv('병원진료'+str(yr)+'.csv', encoding='euc-kr', index=False)

In [25]:
res

주상병코드          H041  H0410  H0411  H0412  H0413  H0414  H0415  H0418
시도코드 요양개시일자
11   20160102     0      0     23      0      0      1      0      1
     20160103     0      0      1      0      0      0      0      0
     20160104     0      0     55      0      0      0      0      5
     20160105     0      0     47      0      0      0      0      5
     20160106     0      0     34      0      0      0      0      4
     20160107     0      0     50      0      0      0      0      2
     20160108     0      0     52      0      0      0      0      3
     20160109     0      0     35      0      0      0      0      1
     20160110     0      0      2      0      0      0      0      0
     20160111     0      0     62      0      0      0      0      3
     20160112     1      0     47      0      0      0      0      4
     20160113     0      0     34      0      0      0      0      3
     20160114     1      0     31      0      0      0      0      6
     20160115     0      0     57      0      0      0      0      4
     20160116     0      0     28      0      0      0      0      3
     20160118     1      0     47      0      0      0      0      5
     20160119     0      0     29      0      0      0      0      2
     20160120     0      0     40      0      0      0      0      1
     20160121     0      0     38      0      0      0      0      1
     20160122     0      0     41      0      0      0      0      8
     20160123     0      0     33      0      0      0      0      0
     20160125     0      0     40      0      0      0      0      4
     20160126     1      0     40      0      0      0      0      5
     20160127     1      0     59      0      0      0      0      4
     20160128     0      0     44      0      0      0      0      4
     20160129     0      0     49      0      0      0      0      5
     20160130     0      0     29      0      0      0      0      1
     20160131     0      0      1      0      0      0      0      0
     20160201     0      0     50      0      0      0      0     11
     20160202     0      0     37      0      0      0      0      7
...             ...    ...    ...    ...    ...    ...    ...    ...
49   20161122     0      0      3      0      0      0      0      0
     20161123     0      0      2      0      0      0      0      2
     20161124     0      0      5      0      0      0      0      0
     20161125     0      0      1      0      0      0      0      1
     20161126     0      0      2      0      0      0      0      0
     20161128     0      0      5      0      0      0      0      0
     20161129     0      0      1      0      0      0      0      0
     20161130     0      0      2      0      0      0      0      0
     20161201     0      0      4      0      0      0      0      0
     20161202     0      0      4      0      0      0      0      0
     20161205     0      0      7      0      0      0      0      0
     20161206     0      0      5      0      0      0      0      0
     20161207     0      0      2      0      0      0      0      0
     20161209     0      0      3      0      0      0      0      1
     20161212     0      0      6      0      0      0      0      0
     20161213     0      0      3      0      0      0      0      0
     20161214     0      0      2      0      0      0      0      0
     20161215     0      0      6      0      0      0      0      0
     20161216     0      0      7      0      0      0      0      1
     20161217     0      0      2      0      0      0      0      0
     20161219     0      0      7      0      0      0      0      0
     20161220     0      0      4      0      0      0      0      1
     20161221     0      0      4      0      0      0      0      0
     20161222     0      0      2      0      0      0      0      0
     20161223     0      0      5      0      0      0      0      0
     20161227     0      0      2      0      0      0      0      1
     20161228     0      0      1      0      0      0      0      0
     20161229     0      0      2      0      0      0      0      0
     20161230     0      0      4      0      0      0      0      0
     20161231     0      0      1      0      0      0      0      0

[5205 rows x 8 columns]