In [1]:
import pandas as pd
import numpy as np

In [46]:
yr = 2016

In [47]:
df = pd.read_csv('da_'+str(yr)+'.csv', encoding='euc-kr')

In [48]:
df

,기준년도,가입자일련번호,진료내역일련번호,성별코드,연령대코드(5세단위),시도코드,요양개시일자,서식코드,진료과목코드,주상병코드,부상병코드,요양일수,입내원일수,심결가산율,심결요양급여비용총액,심결본인부담금,심결보험자부담금,총처방일수,데이터공개일자
0,2016,1,34153116,2,2,45,20160817,3,14,L209,L0888,1,1,0.15,14410,4300,10110,1,20171218
1,2016,2,46374827,2,8,41,20160202,3,1,J209,J304,1,1,0.15,10300,3000,7300,3,20171218
2,2016,2,3115110,2,8,41,20160407,3,1,J209,J304,1,1,0.15,10300,3000,7300,2,20171218
3,2016,2,50348269,2,8,41,20160104,3,1,A099,K291,1,1,0.15,14410,4300,10110,2,20171218
4,2016,2,15822952,2,8,41,20160130,3,13,J40,J304,1,1,0.15,17980,5300,12680,5,20171218
5,2016,2,42990877,2,8,41,20160416,3,13,J40,J304,1,1,0.15,17980,5300,12680,4,20171218
6,2016,2,40156783,2,8,41,20160820,3,13,J40,J304,1,1,0.15,17980,5300,12680,3,20171218
7,2016,2,30696074,2,8,41,20160204,3,13,J40,J304,1,1,0.15,11810,3500,8310,3,20171218
8,2016,2,42883324,2,8,41,20160420,3,13,J40,J304,1,1,0.15,11810,3500,8310,2,20171218
9,2016,2,8473641,2,8,41,20160224,3,13,J40,J304,1,1,0.15,11810,3500,8310,3,20171218
10,2016,2,1564113,2,8,41,20160203,3,1,J029,M1399,1,1,0.15,12340,3700,8640,0,20171218
11,2016,2,12401727,2,8,41,20160328,3,7,M940,R074,1,1,0.25,31730,15800,15930,7,20171218
12,2016,2,12158024,2,8,41,20160316,3,5,S2340,K291,1,1,0.15,25380,7600,17780,3,20171218
13,2016,2,51314132,2,8,41,20161210,3,15,N300,R1039,1,1,0.15,19810,5900,13910,3,20171218
14,2016,2,19876304,2,8,41,20160816,3,15,N300,K297,1,1,0.15,21620,6400,15220,3,20171218
15,2016,2,57400233,2,8,41,20160715,3,13,R42,K296,1,1,0.15,25480,7600,17880,3,20171218
16,2016,3,62655904,2,6,11,20160129,3,1,J209,J060,1,1,0.15,15920,4700,11220,3,20171218
17,2016,3,10328984,2,6,11,20160203,3,13,J042,J304,1,1,0.15,15920,4700,11220,3,20171218
18,2016,3,858036,2,6,11,20160519,3,13,J0390,J060,1,1,0.15,15920,4700,11220,3,20171218
19,2016,3,17499764,2,6,11,20160516,3,13,J0390,J042,1,1,0.15,25500,7600,17900,2,20171218
20,2016,3,17071958,2,6,11,20160402,3,12,H1629,H400,1,1,0.15,33590,10000,23590,1,20171218
21,2016,4,53135011,2,7,29,20160902,3,13,H6640,H628,1,1,0.15,10300,3000,7300,3,20171218
22,2016,4,40109035,2,7,29,20160831,3,13,H6640,J029,1,1,0.15,10300,3000,7300,2,20171218
23,2016,4,53030834,2,7,29,20160924,3,13,J0190,J304,1,1,0.15,12550,3700,8850,7,20171218
24,2016,4,55640558,2,7,29,20160827,3,13,H6640,J029,1,1,0.15,12550,3700,8850,14,20171218
25,2016,4,15779992,2,7,29,20160123,3,13,J0390,J304,1,1,0.15,17980,5300,12680,3,20171218
26,2016,4,54365120,2,7,29,20161010,3,13,H66000,K291,1,1,0.15,17980,5300,12680,4,20171218
27,2016,4,5308192,2,7,29,20160928,3,13,J060,J0190,1,1,0.15,11810,3500,8310,3,20171218
28,2016,4,25159900,2,7,29,20160325,3,4,R222,K297,1,1,0.25,12980,6400,6580,7,20171218
29,2016,4,12375423,2,7,29,20160319,3,4,R222,K297,1,1,0.25,17070,8500,8570,7,20171218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12540317,2016,999996,27467842,1,15,48,20160927,3,13,J4500,J060,1,1,0.15,11920,1500,10420,5,20171218
12540318,2016,999996,51792807,1,15,48,20161230,3,12,H0204,H108,1,1,0.15,13270,1500,11770,0,20171218
12540319,2016,999996,60658488,1,15,48,20160106,3,4,J40,J00,1,1,0.15,12130,1500,10630,2,20171218
12540320,2016,999996,60658487,1,15,48,20160108,3,4,J40,J00,1,1,0.15,12130,1500,10630,2,20171218
12540321,2016,999996,43420228,1,15,48,20160704,3,13,J4500,J060,1,1,0.15,16030,4800,11230,2,20171218
12540322,2016,999996,27643592,1,15,48,20160919,3,13,J4500,J060,1,1,0.15,16030,4800,11230,2,20171218
12540323,2016,999996,19488749,1,15,48,20161116,3,13,J4500,J209,1,1,0.15,16030,4800,11230,3,20171218
12540324,2016,999996,61315709,1,15,48,20160524,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540325,2016,999996,61315712,1,15,48,20160520,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540326,2016,999996,61315713,1,15,48,20160516,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540327,2016,999996,46938802,1,15,48,20160610,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540328,2016,999996,46938801,1,15,48,20160602,3,4,M5456,K297,1,1,0.15,17440,5200,12240,3,20171218
12540329,2016,999996,15587710,1,15,48,20160311,3,4,M5456,J00,1,1,0.15,17350,5200,12150,3,20171218
12540330,2016,999996,53892321,1,15,48,20160615,3,5,M4809,K291,1,1,0.15,21820,6500,15320,2,20171218
12540331,2016,999996,5643888,1,15,48,20160930,3,14,L230,L233,1,1,0.15,16120,4800,11320,4,20171218
12540332,2016,999996,25202721,1,15,48,20160309,3,4,M5456,L500,1,1,0.15,21460,6400,15060,3,20171218
12540333,2016,999997,18473255,1,12,41,20161028,8,0,I109,L309,1,30,0.00,42020,12600,29420,0,20171218
12540334,2016,999997,16624282,1,12,41,20160824,8,0,I109,M6261,1,30,0.00,42020,12600,29420,0,20171218
12540335,2016,999997,51748710,1,12,41,20161227,8,0,I109,M6261,1,30,0.00,42020,12600,29420,0,20171218
12540336,2016,999997,1329853,1,12,41,20160229,8,0,J00,M6261,1,5,0.00,9520,900,8620,0,20171218
12540337,2016,999998,8981599,1,5,27,20160420,3,13,J209,J069,1,1,0.15,14410,4300,10110,3,20171218
12540338,2016,999998,19403294,1,5,27,20161128,3,14,L600,L0220,1,1,0.15,15410,4600,10810,4,20171218
12540339,2016,999998,7684462,1,5,27,20161202,3,14,L600,L0220,1,1,0.15,15410,4600,10810,3,20171218
12540340,2016,999998,19399447,1,5,27,20161126,3,14,L600,L0220,1,1,0.15,17660,5200,12460,1,20171218
12540341,2016,999998,31825051,1,5,27,20160218,3,4,M79170,K30,1,1,0.15,20910,6200,14710,5,20171218
12540342,2016,999998,19569485,1,5,27,20161125,3,14,L600,L0220,1,1,0.15,56560,16900,39660,1,20171218
12540343,2016,999999,47679493,2,9,27,20161117,3,14,L0888,L248,1,1,0.15,14410,4300,10110,3,20171218
12540344,2016,999999,52853246,2,9,27,20160905,3,13,H6038,K297,1,1,0.15,15150,4500,10650,2,20171218
12540345,2016,999999,57327927,2,9,27,20160712,3,12,H0411,H1688,1,1,0.15,16870,5000,11870,1,20171218
12540346,2016,1000000,39962109,2,7,26,20160815,3,12,H109,H108,1,1,0.15,20210,6000,14210,1,20171218

In [49]:
eye = df[df['주상병코드'].str.startswith('H041')]

In [51]:
eye = eye[['시도코드', '요양개시일자', '성별코드', '연령대코드(5세단위)', '주상병코드', '부상병코드']]

In [52]:
res = eye.pivot_table(values=[], index=['시도코드', '요양개시일자'], columns=['성별코드'],
                     aggfunc=len, fill_value=0)

In [53]:
res2 = eye.pivot_table(values=[], index=['시도코드', '요양개시일자'], columns=['연령대코드(5세단위)'],
               aggfunc=len, fill_value=0)

In [54]:
fin = pd.concat([res, res2], axis=1)

In [55]:
names = ['성별코드=1', '성별코드=2']
names.extend(['연령대코드='+str(x) for x in range(1, 19)])
fin.columns = names

In [56]:
fin['전체빈도'] = fin['성별코드=1'] + fin['성별코드=2']

In [57]:
fin = fin.reset_index()

In [59]:
fin.to_csv('병원진료'+str(yr)+'.csv', encoding='euc-kr', index=False)

In [58]:
fin

,시도코드,요양개시일자,성별코드=1,성별코드=2,연령대코드=1,연령대코드=2,연령대코드=3,연령대코드=4,연령대코드=5,연령대코드=6,...,연령대코드=10,연령대코드=11,연령대코드=12,연령대코드=13,연령대코드=14,연령대코드=15,연령대코드=16,연령대코드=17,연령대코드=18,전체빈도
0,11,20160102,8,17,0,1,2,2,1,3,...,4,1,1,1,2,1,2,0,0,25
1,11,20160103,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
2,11,20160104,19,41,1,0,0,1,1,4,...,4,5,3,8,6,10,4,5,1,60
3,11,20160105,18,34,0,0,2,0,3,4,...,9,3,6,4,7,3,4,0,0,52
4,11,20160106,10,28,1,0,0,0,4,5,...,6,3,6,2,2,1,1,0,1,38
5,11,20160107,23,29,0,0,1,1,1,3,...,6,6,6,6,2,0,6,1,0,52
6,11,20160108,19,36,0,0,0,0,6,2,...,4,10,4,4,5,3,1,2,2,55
7,11,20160109,11,25,0,0,1,2,0,3,...,2,3,2,4,3,3,3,2,0,36
8,11,20160110,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
9,11,20160111,21,44,1,0,0,0,5,4,...,1,5,6,10,7,4,3,1,2,65
10,11,20160112,14,38,0,1,0,3,6,5,...,5,1,1,3,2,5,3,2,1,52
11,11,20160113,10,27,0,0,3,1,0,5,...,3,1,5,4,2,3,1,1,0,37
12,11,20160114,11,27,0,0,1,1,0,4,...,0,2,8,5,4,6,3,1,0,38
13,11,20160115,18,43,0,1,2,0,3,9,...,3,5,5,5,1,8,5,2,2,61
14,11,20160116,13,18,0,0,0,1,0,6,...,2,4,3,3,1,1,2,0,0,31
15,11,20160118,10,43,0,0,0,0,2,5,...,4,7,6,3,8,4,2,2,3,53
16,11,20160119,9,22,0,0,3,0,0,2,...,2,4,2,2,4,3,2,1,0,31
17,11,20160120,11,30,0,1,0,3,2,3,...,6,0,7,1,4,3,1,0,1,41
18,11,20160121,13,26,0,1,1,1,4,0,...,4,2,1,5,3,4,3,1,0,39
19,11,20160122,11,38,0,1,4,0,1,1,...,2,5,5,7,3,3,4,3,0,49
20,11,20160123,8,25,0,0,2,3,2,3,...,4,5,2,2,2,1,1,0,0,33
21,11,20160125,19,25,0,0,0,1,3,3,...,6,3,2,5,4,3,3,0,0,44
22,11,20160126,10,36,0,0,0,1,2,2,...,6,2,3,5,5,5,3,2,0,46
23,11,20160127,18,46,0,2,2,2,5,6,...,6,4,7,6,3,4,6,2,1,64
24,11,20160128,17,31,1,2,1,0,1,1,...,1,3,5,3,3,9,1,2,3,48
25,11,20160129,11,43,0,1,0,2,3,4,...,4,6,5,5,5,3,4,1,2,54
26,11,20160130,15,15,0,1,0,1,0,2,...,2,2,3,4,3,3,2,0,0,30
27,11,20160131,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
28,11,20160201,17,44,0,0,0,1,4,5,...,1,12,5,6,4,8,7,3,1,61
29,11,20160202,13,31,0,1,0,4,5,0,...,2,1,3,7,3,3,3,2,2,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5175,49,20161122,1,2,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,3
5176,49,20161123,1,3,0,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,4
5177,49,20161124,1,4,0,0,0,0,0,0,...,0,1,2,1,1,0,0,0,0,5
5178,49,20161125,1,1,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,2
5179,49,20161126,0,2,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,2
5180,49,20161128,1,4,0,0,0,0,0,2,...,0,0,0,1,0,0,1,1,0,5
5181,49,20161129,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
5182,49,20161130,1,1,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,2
5183,49,20161201,2,2,0,0,0,0,0,0,...,1,0,1,0,0,1,0,1,0,4
5184,49,20161202,2,2,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,4
5185,49,20161205,0,7,0,0,0,0,0,1,...,0,2,1,1,0,1,1,0,0,7
5186,49,20161206,0,5,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,0,5
5187,49,20161207,2,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,2
5188,49,20161209,1,3,0,0,0,0,0,0,...,0,1,1,0,0,1,0,1,0,4
5189,49,20161212,3,3,0,0,0,0,0,0,...,1,0,0,1,1,2,0,0,0,6
5190,49,20161213,1,2,0,0,0,0,0,0,...,1,0,0,0,0,1,1,0,0,3
5191,49,20161214,1,1,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,2
5192,49,20161215,1,5,0,0,0,0,0,0,...,0,1,1,0,0,2,1,1,0,6
5193,49,20161216,1,7,0,0,0,0,1,1,...,0,0,2,1,0,0,2,0,0,8
5194,49,20161217,0,2,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,2
5195,49,20161219,1,6,0,0,0,0,1,0,...,1,0,0,2,2,0,0,0,0,7
5196,49,20161220,2,3,0,0,0,0,1,1,...,0,0,0,0,0,2,1,0,0,5
5197,49,20161221,1,3,0,0,0,0,0,1,...,0,1,0,0,1,0,0,0,0,4
5198,49,20161222,1,1,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,2
5199,49,20161223,3,2,0,0,0,0,1,0,...,0,0,1,0,0,2,1,0,0,5
5200,49,20161227,1,2,0,0,0,0,0,0,...,0,1,2,0,0,0,0,0,0,3
5201,49,20161228,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
5202,49,20161229,1,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,2
5203,49,20161230,1,3,0,0,0,0,0,0,...,0,2,0,0,0,1,0,0,0,4
5204,49,20161231,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1